#!/usr/bin/env python
#encoding=utf-8
import redis,json,datetime
r=redis.Redis()

user = dict()
user["id"]=1
user["username"]="mlzboy"
user["password"]="1"
user["createdon"]=datetime.datetime.now()


